# Generated by Django 5.0.1 on 2024-01-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
